django_level4/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^other/', views.other, name='other'),
    url(r'^relative/', views.relative, name='relative'),
    url(r'^base/', views.base, name='base'),
]

django_level4/django_level4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
]

django_level4/basic_app/models.py
from django.db import models

# Create your models here.

django_level4/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':"Hello World", 'number':100}
    return render(request,'basic_app/index.html', context=context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative.html')

def base(request):
    return render(request, 'basic_app/base.html')

django_level4/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Link</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">The Other Page</a></li>
        </ul>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

django_level4/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

  {% block body_block %}
    {% load my_extras %}
    <h1>Welcome to the Index Page!</h1>
    <h2>Go to /others</h2>
    <h3>{{ text|cut_out:'World' }}</h3>
    <h3>{{number|add:"99"}}</h3>
  {% endblock %}

django_level4/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to the Other Page!</h1>
    <h2>This is an example of Template Inheritance</h2>
    <p><a href="{% url 'basic_app:relative' %}">Link to the relative Page</a></p>
  {% endblock %}

django_level4/templates/basic_app/relative.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Page</title>
  </head>
  <body>
    <h1>Welcome to the Relative Page!</h1>
  </body>
</html>